### ISSUE TITLE
Not an issue, sound related suggestion

### ISSUE THREAD

**Issue by clank201** [AdamFx990/FF3DS-clone#2]
I saw you starred my 3dssoundexample repository and added audio to your homebrew, check this out: https://github.com/clank201/Rogue3DS/blob/99d1ede0b275565e169897cd8317d7f367fd8418/source/sound.cpp

you can then use ogg vorbis files without having to mess with raw pcm sound, and it won't load the whole file in ram, instead streaming it while it plays, letting you play kinda big sound files. I'll try to update the 3dssoundexample with something more robust when I have some time, but for now the link above is better than that.

EDIT: I've just seen that you only use sound effects, so it shouldn't be a problem for now to use raw sound files. I'll try to put something together to use .ogg as background music AND sound effects soon.

**Comment by AdamFx990** [comment]
Yeah I saw that. I couldn't get it working in C though.  There is still a flac decoder in there that just isn't utilised. I'm not really a fan of the idea of using ogg as it involves coverting all the existing audio files I have lined up.
